# ptpython/keywords/matplotlib_builtins.py

"""
Este módulo contém as traduções das funções embutidas do Matplotlib para o português.
"""

BUILTINS = {
    "plotar": "plot",
    "subfiguras": "subplots",
    "linha": "line",
    "barra": "bar",
    "barra_horizontal": "barh",
    "histograma": "hist",
    "dispersão": "scatter",
    "imagem": "imshow",
    "contorno": "contour",
    "contorno_preenchido": "contourf",
    "pcolor": "pcolor",
    "pcolormesh": "pcolormesh",
    "quiver": "quiver",
    "streamplot": "streamplot",
    "exibir": "show",
    "salvar": "savefig",
    "legenda": "legend",
    "título": "title",
    "xrotulo": "xlabel",
    "yrotulo": "ylabel",
    "xmarcas": "xticks",
    "ymarcas": "yticks",
    "limites": "axis",
    "xlim": "xlim",
    "ylim": "ylim",
    "grade": "grid",
    "texto": "text",
    "anotar": "annotate",
    "barra_de_cores": "colorbar",
    "clabel": "clabel",
    "polar": "polar",
    "loglog": "loglog",
    "semilogx": "semilogx",
    "semilogy": "semilogy",
    "twinx": "twinx",
    "twiny": "twiny",
    "ajuste_de_subfiguras": "subplots_adjust",
    "adicionar_subfigura": "add_subplot",
    "título_do_conjunto": "suptitle",
    "eixos": "axes",
    "projeção": "projection",
    "formatar_xdata": "format_xdata",
    "formatar_ydata": "format_ydata",
}