# ptpython/keywords/matplotlib_keywords.py

"""
Este módulo contém as traduções das palavras-chave do Matplotlib para o português.
"""

KEYWORDS = {
    "gráfico": "plot",
    "figura": "figure",
    "subplots": "subplots",
    "linha": "line",
    "barra": "bar",
    "barra_horizontal": "barh",
    "histograma": "hist",
    "dispersão": "scatter",
    "imagem": "imshow",
    "contorno": "contour",
    "contorno_filled": "contourf",
    "pcolor": "pcolor",
    "pcolormesh": "pcolormesh",
    "quiver": "quiver",
    "streamplot": "streamplot",
    "exibir": "show",
    "salvar": "savefig",
    "legenda": "legend",
    "título": "title",
    "xlabel": "xlabel",
    "ylabel": "ylabel",
    "xticks": "xticks",
    "yticks": "yticks",
    "limites": "axis",
    "xlim": "xlim",
    "ylim": "ylim",
    "grade": "grid",
    "texto": "text",
    "anotar": "annotate",
    "colorbar": "colorbar",
    "clabel": "clabel",
    "polar": "polar",
    "loglog": "loglog",
    "semilogx": "semilogx",
    "semilogy": "semilogy",
    "twinx": "twinx",
    "twiny": "twiny",
    "subfigura_ajuste": "subplots_adjust",
    "add_subplot": "add_subplot",
    "conjunto_título": "suptitle",
    "eixos": "axes",
    "projeção": "projection",
    "formatar_xdata": "format_xdata",
    "formatar_ydata": "format_ydata",
    "salvarfigura": "savefig",
    "marcador": "marker",
    "cor": "color",
    "configurar_título": "set_title",
}