# ptpython/keywords/python_keywords.py

"""
Este módulo contém as traduções das palavras-chave do Python para o português.
"""

KEYWORDS = {
    "se": "if",
    "senão": "else",
    "senão se": "elif",
    "para": "for",
    "enquanto": "while",
    "função": "def",
    "retornar": "return",
    "classe": "class",
    "importar": "import",
    "de": "from",
    "como": "as",
    "tentar": "try",
    "exceto": "except",
    "finalmente": "finally",
    "com": "with",
    "passar": "pass",
    "continuar": "continue",
    "interromper": "break",
    "verdadeiro": "True",
    "falso": "False",
    "nulo": "None",
    "global": "global",
    "nãolocal": "nonlocal",
    "é": "is",
    "não é": "is not",
    "em": "in",
    "não em": "not in",
    "e": "and",
    "ou": "or",
    "não": "not",
    "lançar": "raise",
    "afirmar": "assert",
    "eliminar": "del",
    "caso": "case",
    "corresponder": "match",
    "gerar": "yield",
    "importar": "import",
    "carregar": "load",
    "configurar": "setup",
    "adicionar": "add",
    "remover": "remove",
    "criar": "create",
    "deletar": "delete",
    "atualizar": "update",
    "selecionar": "select",
    "inserir": "insert",
    "definir": "set",
    "conectar": "connect",
    "desconectar": "disconnect",
    "iniciar": "start",
    "parar": "stop",
    "pausar": "pause",
    "reiniciar": "restart",
    "executar": "run",
    "testar": "test",
    "depurar": "debug",
    "compilar": "compile",
    "configuração": "settings",
    "procurar": "search",
    "encontrar": "find",
    "substituir": "replace",
    "transformar": "transform",
    "validar": "validate",
    "verificar": "check",
    "comparar": "compare",
    "imprimir": "print",
    "ler": "read",
    "escrever": "write",
    "enviar": "send",
    "receber": "receive",
    "baixar": "download",
    "upload": "upload",
    "importar_modulo": "import_module",
    "executar_script": "run_script",
}