BUILTINS = {
    "imprimir": "print",
    "entrada": "input",
    "inteiro": "int",
    "flutuante": "float",
    "cadeia": "str",
    "lista": "list",
    "dicionário": "dict",
    "conjunto": "set",
    "tupla": "tuple",
    "soma": "sum",
    "mapear": "map",
    "filtro": "filter",
    "lambda": "lambda",
    "abrir": "open",
    "comprimento": "len",
    "intervalo": "range",
    "enumerar": "enumerate",
    "tudo": "all",
    "qualquer": "any",
    "tipo": "type",
    "éinstância": "isinstance",
    "tematributo": "hasattr",
    "obteratributo": "getattr",
    "definiratributo": "setattr",
    "eliminaratributo": "delattr",
}
