KEYWORDS = {
    "se": "if",
    "senão": "else",
    "senão se": "elif",
    "para": "for",
    "enquanto": "while",
    "função": "def",
    "retornar": "return",
    "classe": "class",
    "importar": "import",
    "de": "from",
    "como": "as",
    "tentar": "try",
    "exceto": "except",
    "finalmente": "finally",
    "com": "with",
    "passar": "pass",
    "continuar": "continue",
    "interromper": "break",
    "verdadeiro": "True",
    "falso": "False",
    "nulo": "None",
    "global": "global",
    "não local": "nonlocal",
    "é": "is",
    "não é": "is not",
    "em": "in",
    "não em": "not in",
    "e": "and",
    "ou": "or",
    "não": "not",
    "levantar": "raise",
    "afirmar": "assert",
    "eliminar": "del",
    "caso": "case",
    "corresponder": "match",
    "rendição": "yield",
    "exceto": "except",
}